routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SujetController;
use App\Http\Controllers\ReponseController;
use App\Http\Controllers\CandidatController;
use App\Http\Controllers\QuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('qcm.index');
});

Route::get('/qcm_staff', [CandidatController::class, 'showQcmElaboration'])->name('qcm_staff');

Route::resource('candidat', CandidatController::class);
Route::resource('sujet', SujetController::class);
Route::resource('question', QuestionController::class);
Route::resource('reponse', ReponseController::class);
Route::get('/reponse/add/{id_question}', [ReponseController::class, 'storeReponse'])->name('question.reponse.store');

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Candidat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Candidat extends Model
{
    use HasFactory;
    protected $fillable = ['nom'];
}

app/Http/Controllers/CandidatController.php
<?php

namespace App\Http\Controllers;

use App\Models\Candidat;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CandidatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'nom' => 'required',
        ];

        $validate = Validator::make($request->all(), $rules);

        if($validate->fails()){
            return response()->json([
                'warning'=>$validate->errors()
            ]);
        }

        $datas= [
            'nom' => $request->nom,
        ];
        
        try {
            Candidat::create($datas);
            $candidats = $this->getLastCandidates();

            return redirect()->route('qcm_staff', compact('candidats'));
        } catch (\Throwable $th) {
            return response()->json([
                'error'=>$th->getMessage()
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        dd("show");
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $nom = $request->nom;
        $rules = [
            'nom' => 'required',
        ];

        $validate = Validator::make($request->all(), $rules);

        if($validate->fails()){
            return response()->json([
                'warning'=>$validate->errors()
            ]);
        }

        $datas= [
            'nom' => $nom,
        ];
        
        try {
            $candidate = Candidat::find($id);
            $candidate->nom = $nom;
            $candidate->save();
            $candidats = $this->getLastCandidates();

            return redirect()->route('qcm_staff', compact('candidats'));
        } catch (\Throwable $th) {
            return response()->json([
                'error'=>$th->getMessage()
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getLastCandidates()
    {
        try {
            return $candidats = Candidat::orderByDesc('id')->limit(3)->get();
        } catch (\Throwable $th) {
            return response()->json([
                'error'=>$th->getMessage()
            ]);
        }
    }

    public function showQcmElaboration()
    {
        $candidats = $this->getLastCandidates();

        return view('qcm.staff.candidat.create', compact('candidats'));
    }
}

resources/views/qcm/staff/candidat/create.blade.php
@extends('layouts.qcm_app')
@section('content')
    <div class="modal fade" id="editModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form id="updateCandidate" class="form" method="POST">
                    @csrf
                    @method('PUT')
                    {{-- HTML Forms does not support PUT, PATCH, DELETE -- so we define Form method Spoofing --}}

                    <div class="modal-header">
                        <h4 class="modal-title">Modifier le candidat</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="col-mr-2">
                            <label for="nom">Nom du candidat</label>
                            <input type="text" name="nom" id="nomToUpdate" class="form-control" >
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Annuler</button>
                        <button type="submit" class="btn btn-warning" >Confirmer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <h2>Elaborer le qcm</h2>
    <hr>
    <h3>Ajout d'un candidat:</h3>
    <form id="addCandidate" class="form-inline" action="{{ route('candidat.store') }}" method="POST">
        @csrf
        <div class="col-mr-2">
            <label for="nom">Nom du candidat</label>
            <input type="text" name="nom" id="mom" class="form-control" placeholder="Ecrivez le nom ici ...">
        </div>
        <div class="col mt-4">
            <button class="btn btn-primary" type="submit" >
                Ajouter
            </button>
        </div>
    </form>
    <hr>
    <strong>Les 3 nouveaux candidats</strong> <br>
    <a href="">Voir la liste complète >></a>
    <table class="table table-hover table-bordered">
        <thead class="thead-dark">
            <th>Numéros</th>
            <th>Nom</th>
            <th>Actions</th>
        </thead>
        @if ($candidats)
            @foreach ($candidats as $item)
            <tr>
                <td>{{ $item->id }}</td>
                <td>{{ $item->nom }}</td>
                <td id="action">
                    <a id="idToEdit" data-name="{{ $item->nom }}" data-action="{{ route('candidat.update', $item->id) }}" class="btn btn-warning btn-sm" data-toggle="modal" data-target="#editModal">Modifier</a>
                    <a href="" class="btn btn-danger btn-sm">Supprimer</a>
                </td>
            </tr>
            @endforeach
        @endif
    </table>
    <hr>
    <div class="btn_right_aligned">
        <a href="{{ route('sujet.create') }}" type="button" class="btn btn-primary btn-lg">Suivant</a>
    </div>
@endsection
@section('js')
    <script>
        $(document).ready(function () {
            var $modalEdit = $('#updateCandidate')
            var $table = $("table").find("tr")
            var $edit = $table.find("#idToEdit")
            $edit.each(function(){
                $(this).click(function(){
                    var action = $(this).data('action')
                    var name = $(this).data('name')
                    $modalEdit.attr('action', action)
                    $modalEdit.find("#nomToUpdate").val(name)
                })
            })
        });
    </script>
@endsection