routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SujetController;
use App\Http\Controllers\ReponseController;
use App\Http\Controllers\CandidatController;
use App\Http\Controllers\QuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('qcm.index');
});

Route::get('/qcm_staff', [CandidatController::class, 'showQcmElaboration'])->name('qcm_staff');

Route::resource('candidat', CandidatController::class);
Route::resource('sujet', SujetController::class);
Route::resource('question', QuestionController::class);
Route::resource('reponse', ReponseController::class);
Route::get('/reponse/add/{id_question}', [ReponseController::class, 'storeReponse'])->name('question.reponse.store');

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'titre',
        'question',
        'id_sujet',
    ];
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Question;
use Illuminate\Http\Request;
use App\Http\Controllers\SujetController;
use Illuminate\Support\Facades\Validator;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sujet = new SujetController();
        $lastSujet = $sujet->getLastSujet();
        $questions = Question::all();

        return view('qcm.staff.question.create', compact([
            'lastSujet',
            'questions',
            ]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $sujet = new SujetController();
        $lastSujet = $sujet->getLastSujet();
        $sujetId = $lastSujet->id;
        $titre = $request->titre;
        $question = $request->question;

        $rules = [
            'titre' => 'required',
            'question' => 'required',
        ];

        $validate = Validator::make($request->all(), $rules);

        if($validate->fails()){
            return response()->json([
                'warning'=>$validate->errors()
            ]);
        }

        $datas= [
            'id_sujet' => $sujetId,
            'titre' => $titre,
            'question' => $question,
        ];
        
        try {
            Question::create($datas);
            $questions = Question::all();

            return redirect()->route('question.create', compact('questions'));
        } catch (\Throwable $th) {
            return response()->json([
                'error'=>$th->getMessage()
            ]);
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/qcm/staff/question/create.blade.php
@extends('layouts.qcm_app')
@section('content')
    <div class="modal fade" id="reponseModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form id="updateCandidate" class="form" method="POST">
                    @csrf
                    @method('PUT')
                    {{-- HTML Forms does not support PUT, PATCH, DELETE -- so we define Form method Spoofing --}}

                    <div class="modal-header">
                        <h4 class="modal-title">Ajouter une réponse</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="col-mr-2">
                            <label for="nom">La réponse</label>
                            <input type="text" name="reponse" id="reponse" class="form-control" >
                        </div>
                        <div class="col-mr-2">
                            <label for="nom">Evaluer à:</label>
                            
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Annuler</button>
                        <button type="submit" class="btn btn-warning" >Confirmer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <h2>Implémentation du question</h2>
    <hr>
    <h2>Le sujet:</h2>
    <p>Le titre: </p>
    {{ $lastSujet->titre ?? 'Aucun titre à afficher' }}
    <p>Le sujet: </p>
    @if ($lastSujet)
        {!! html_entity_decode($lastSujet->le_sujet) !!}
    @endif
    <span>Aucun sujet à afficher</span>
    <hr>
    <h2>Ajouter une question</h2>
    <form action="{{ route('question.store') }}" method="post">
        @csrf

        <div class="form-group">
            <label for="">Label du question</label>
            <input type="text" class="form-control" name="titre">
        </div>
        <div class="form-group">
            <label for="">La question</label>
            <textarea name="question" class="form-control" id="" cols="30" rows="5"></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Ajouter</button>
        </div>
    </form>
    <hr>
    <h3>Les questions à propos du sujet:</h3>
    <table class="table table-hover table-bordered">
        <thead>
            <th>Numéro</th>
            <th>Label Question</th>
            <th>La question</th>
            <th>Actions</th>
        </thead>
        @foreach ($questions as $item)
        <tbody>
            <td>{{ $item->id ?? '-' }}</td>
            <td>{{ $item->titre ?? '-' }}</td>
            <td>{{ $item->question ?? '-' }}</td>
            <td>
                <a id="addResponse" data-action="{{ route('reponse.store', $item->id) }}" class="btn btn-success btn-sm" data-toggle="modal" data-target="#reponseModal">Ajout des reponses</a>
            </td>
        </tbody>
        @endforeach
    </table>
@endsection
@section('js')
    <script>
        var $modalEdit = $('#updateCandidate')
        var $table = $("table").find("tr")
        var $edit = $table.find("#idToEdit")
        $edit.each(function(){
            $(this).click(function(){
                var action = $(this).data('action')
                var name = $(this).data('name')
                $modalEdit.attr('action', action)
                $modalEdit.find("#nomToUpdate").val(name)
            })
        })
    </script>
@endsection