routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SujetController;
use App\Http\Controllers\ReponseController;
use App\Http\Controllers\CandidatController;
use App\Http\Controllers\QuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('qcm.index');
});

Route::get('/qcm_staff', [CandidatController::class, 'showQcmElaboration'])->name('qcm_staff');

Route::resource('candidat', CandidatController::class);
Route::resource('sujet', SujetController::class);
Route::resource('question', QuestionController::class);
Route::resource('reponse', ReponseController::class);
Route::get('/reponse/add/{id_question}', [ReponseController::class, 'storeReponse'])->name('question.reponse.store');

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Sujet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sujet extends Model
{
    use HasFactory;
    protected $fillable = [ "titre", "le_sujet" ];
}

app/Http/Controllers/SujetController.php
<?php

namespace App\Http\Controllers;

use App\Models\Sujet;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class SujetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('qcm.staff.sujet.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $sujet = htmlentities($request->le_sujet);
        $titre = $request->titre;

        $rules = [
            'titre' => 'required',
            'le_sujet' => 'required',
        ];

        $validate = Validator::make($request->all(), $rules);

        if($validate->fails()){
            return response()->json([
                'warning'=>$validate->errors()
            ]);
        }

        $datas= [
            'titre' => $titre,
            'le_sujet' => $sujet,
        ];
        
        try {
            Sujet::create($datas);
            $lastSujet = $this->getLastSujet();

            return redirect()->route('question.create', compact('lastSujet'));
        } catch (\Throwable $th) {
            return response()->json([
                'error'=>$th->getMessage()
            ]);
        }
    }

    public function getLastSujet()
    {
        try {
            return $sujet = Sujet::latest()->first();
        } catch (\Throwable $th) {
            return response()->json([
                'error'=>$th->getMessage()
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/qcm/staff/sujet/create.blade.php
@extends('layouts.qcm_app')
@section('content')
    <h2>Elaborer le qcm</h2>
    <hr>
    <h3>Ajouter un sujet:</h3>
    <form id="addSujet" method="POST">
        @csrf

        <div class="form-group">
            <label for="">Titre du sujet</label>
            <input type="text" name="titre" class="form-control">
        </div>
        <div class="form-group">
            <label for="">Le contenu</label>
            <div id="editor"></div>
            <input hidden type="text" name="le_sujet" id="sujet">
        </div>
        <button type="submit" id="addSujetBtn" class="btn btn-primary">Suivant</button>
    </form>
    <hr>
@endsection
@section('js')
<script src="{{ asset('ckeditor5-build-classic/ckeditor.js') }}"></script>
<script>
    ClassicEditor
        .create(document.querySelector('#editor'))
        .catch(error => {
            console.error(error)
        })

    var $btn = $("#addSujetBtn")
    
    // TODO: Handle button disabled when input not filled
    
    $btn.click(function(){
        var $ck = $(".ck-content")
        var $htmlVal = $ck.html()
        var sujet = $("#sujet")
        var $initialParagraph = $ck.find("p")
        var $initialBr = $initialParagraph.find("br")
        var ckFiller = $initialBr.data("cke-filler")
        if(ckFiller == true){
            sujet.val("")    
        }else{
            sujet.val($htmlVal)
        }
        $("#addSujet").attr("action", "{{ route("sujet.store") }}")
    })
</script>
@endsection